- name: dbeaver
  hosts: 127.0.0.1
  connection: local

  tasks:

    - name: Add dbeaver ppa
      become: yes
      apt_repository:
        repo: ppa:serge-rider/dbeaver-ce
        update_cache: yes
        validate_certs: no

    # - name: Update APT package list
    #   become: yes
    #   apt:
    #     update_cache: yes
    #   when: apt_repository.changed
    #   register: apt_update
    #   retries: 5
    #   until: apt_update is success

    - name: Install dbeaver (Linux)
      become: yes
      apt:
        package: dbeaver-ce

