- name: Install fzf
  hosts: localhost
  tasks:
    - name: Ensure git is installed
      package:
        name: git
        state: present

    - name: Clone fzf repository
      git:
        repo: 'https://github.com/junegunn/fzf.git'
        dest: '~/.fzf'
        depth: 1
        update: no  # Do not update if it already exists

    - name: Run fzf install script
      command: '~/.fzf/install'
      args:
        executable: /bin/bash
      when: false && ansible_env.SHELL is defined and ansible_env.SHELL != ''

    - name: Run fzf install script
      shell: '~/.fzf/install'
      when: ansible_env.SHELL is defined and ansible_env.SHELL != ''
