- name: XPRA
  hosts: 127.0.0.1
  connection: local

  tasks:

    - name: Add XPRA APT package key
      become: yes
      apt_key:
        url: https://winswitch.org/gpg.asc

    - name: Add XPRA APT package repository
      become: yes
      apt_repository:
        repo: deb http://winswitch.org/ {{ ansible_distribution_release }} main
        filename: winswitch
        update_cache: no
      register: apt_repository

    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      when: apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install XPRA (Linux)
      become: yes
      apt:
        package: xpra

