- name: Spotify
  hosts: 127.0.0.1
  connection: local

  tasks:

    - name: Add Spotify APT package key
      become: yes
      apt_key:
        url: https://download.spotify.com/debian/pubkey_0D811D58.gpg

    - name: Add Spotify APT package repository
      become: yes
      apt_repository:
        repo: deb http://repository.spotify.com stable non-free
        filename: spotify
        update_cache: no
      register: apt_repository

    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      when: apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install Spotify (Linux)
      become: yes
      apt:
        package: spotify-client

