- name: Emacs
  hosts: 127.0.0.1
  connection: local

  tasks:
      - name: Add Emacs APT package repository (Ubuntu)
        become: yes
        apt_repository:
            repo: ppa:kelleyk/emacs
            filename: emacs
            update_cache: no
        register: apt_repository_1

      - name: Update APT package list
        become: yes
        apt:
            update_cache: yes
        when: apt_repository_1.changed
        register: apt_update
        retries: 5
        until: apt_update is success

      - name: Install Emacs 27
        become: yes
        apt:
            package: emacs27
