- name: Fonts
  hosts: 127.0.0.1
  connection: local

  tasks:
      - name: Get Jetbrain mono fonts
        unarchive:
            src: https://download.jetbrains.com/fonts/JetBrainsMono-2.225.zip
            dest: ~/.local/share/fonts
            remote_src: yes
        register: fonts_downloaded

      - name: Update font cache
        become: yes
        command: fc-cache -sv
        when: fonts_downloaded.changed
